### Registrazione
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "test",
  "password": "Palapala1%",
  "email": "gabrielepalaj@hotmail.com"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "gabrielepalaj",
  "password": "Gabriele13!"
}



